### DISCUSSION TITLE
Host Machine Unable To Trigger Zerotier One localhost:9993 API? Now Have Connection Refused Error

### DISCUSSION THREAD

**Discussion by jerrychong25** [dec0dOS/zero-ui#102] [Q&A] [answered]
Hi all,

I would like to trigger Zerotier localhost:9993 API from host machine (Where it run docker compose up command) as mentioned in https://docs.zerotier.com/self-hosting/network-controllers/#authorize-a-member.

Unfortunately, it have this error when running the command on the host machine:
```
ubuntu@host-machine:~/xxxxxx-vpn-server/backup$ curl -X POST "http://localhost:9993/controller/network/XXXXXXXXXXXXXXXX/member/XXXXXXXXXX" -H "X-ZT1-AUTH: AUTH_STRING_HERE" -d '{"authorized": true}'

curl: (7) Failed to connect to localhost port 9993 after 0 ms: Connection refused
```

Any solution to solve?

I've tried use following solutions to fix it:
- sudo ufw allow 9993/tcp
- echo "{\"settings\": {\"portMappingEnabled\": true,\"softwareUpdate\": \"disable\",\"allowManagementFrom\": [\"0.0.0.0/0\"]}}" > /var/lib/zerotier-one/local.conf

Unfortunately, both does not solved my issues either.

Thank you.

**Comment by jerrychong25** [comment, marked as answer]
Problem solved with using following docker compose codes on **zerotier** section:
```
  zerotier:
    image: zyclonite/zerotier:1.10.1
    container_name: zu-controller
    restart: unless-stopped
    volumes:
      - controller_data:/var/lib/zerotier-one
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0
    ports:
      - "9993:9993/tcp"
      - "9993:9993/udp"
```

For more details, can refer to https://github.com/zyclonite/zerotier-docker/issues/17#issuecomment-1214208082
