### DISCUSSION TITLE
Zero-ui docker-compose stuck at attachment phase

### DISCUSSION THREAD

**Discussion by Athlon1323** [dec0dOS/zero-ui#121] [General]
Greetings, everyone. 
I have encountered an problem with my custom zero-ui deployment. I am trying to setup nginx as a reverse proxy, and after commenting out the caddy image in docker compose, zu-controller and zu-main are stuck in attaching phase. I am unable to troubleshoot this issue, because no logs are created, and this behaviour repeats itself if I am using other ports. I am attaching the docker compose file below, and  would be glad, if somebody could point me in the right direction.

```
version: "3"

services:
  zerotier:
    image: zyclonite/zerotier:1.10.1
    container_name: zu-controller
    restart: unless-stopped
    volumes:
      - ./zerotier-one:/var/lib/zerotier-one
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0
    expose:
      - "9993/tcp"
    ports:
      - "9993:9993/udp"
  zero-ui:
    image: dec0dos/zero-ui:latest
    container_name: zu-main
    build:
      context: .
      dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
   # depends_on:
   #   - zerotier
    volumes:
      - ./zerotier-one:/var/lib/zerotier-one
      - ./data:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://zerotier:9993/
      - ZU_SECURE_HEADERS=true
      - ZU_DEFAULT_USERNAME=someuser
      - ZU_DEFAULT_PASSWORD= SOmepassword
    expose:
      -  "4000/tcp"
  #  ports:
  #    -  "4000:4000/tcp"

 # https-proxy:
 #   image: caddy:latest
 #   container_name: zu-https-proxy
 #   restart: unless-stopped
 #   depends_on:
 #     - zero-ui
 #   command: caddy reverse-proxy --from mydomain.domain.com --to zero-ui:4000
 #   volumes:
 #     - ./caddy:/data/caddy
 #   ports:
 #     - "80:80"
 #     - "443:443"


```
