### DISCUSSION TITLE
Can I use the official zerotier docker image?

### DISCUSSION THREAD

**Discussion by maxin-cn** [dec0dOS/zero-ui#129] [Q&A]
I used zerotier's official docker image and my docker-compose file is as follows (also I disable the https):
```
version: "3"

services:
  zerotier:
    image: zerotier/zerotier:1.10.2
    container_name: zu-controller
    restart: unless-stopped
    volumes:
      - ./zerotier-one:/var/lib/zerotier-one
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0
    cap_add:
      - ALL
    privileged: true
    devices:
      - /dev/net/tun
    expose:
      - "9993/tcp"
    ports:
      - "9993:9993/udp"
  zero-ui:
    image: dec0dos/zero-ui:latest
    container_name: zu-main
    build:
      context: .
      dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
    depends_on:
      - zerotier
    volumes:
      - ./zerotier-one:/var/lib/zerotier-one
      - ./data:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://zerotier:9993/
      - ZU_SECURE_HEADERS=false
      - ZU_DEFAULT_USERNAME=admin
      - ZU_DEFAULT_PASSWORD=zero-ui
    ports:
      - "4000"
```
But I kept encountering the following problem -zerotier wouldn't start. How can I solve this problem? Thanks~
![image](https://user-images.githubusercontent.com/38418898/209066283-3bb28824-0b99-4e9e-9c85-d8ebcf0f140d.png)

**Comment by dec0dOS** [comment]
Hello, @maxin-cn!

Seems to be something wrong with your docker installation. Docker from snap is really garbage, please try to use it from the apt.

**Reply by maxin-cn** [reply]
I separately tried using the commands that come with the zerotier official docker:
`docker run --name myzerotier --rm --cap-add NET_ADMIN --device /dev/net/tun zerotier/zerotier:latest`
I found it didn't work properly either.
BTW, I read the discussion on github, it seems that there are other zerotier images that can be used? For example, `zerotier/ Zerotier-synology`

**Reply by dec0dOS** [reply]
I could not guarantee that other images are going to work. Controller function should enabled there to work properly.

**Reply by dec0dOS** [reply]
ZeroUI used to build images before
https://github.com/dec0dOS/zero-ui/blob/ead11f11e187d18edef4c63a845be9582ab54273/docker/zerotier/Dockerfile

But for now  
`zyclonite/zerotier` is used.

**Reply by dec0dOS** [reply]
https://hub.docker.com/r/zerotier/zerotier is not going to work. You should patch it like this
https://github.com/dec0dOS/zero-ui/blob/ead11f11e187d18edef4c63a845be9582ab54273/docker/zerotier/Dockerfile#L4

**Reply by maxin-cn** [reply]
The Zerotier image can be replaced with `zerotier/ Zerotier-synology` to run successfully. just add `zero-ui/docker/zerotier/Dockerfile` . The content in Dockerfile is here:
```
FROM zerotier/zerotier-synology:latest

# RUN apk add --no-cache zerotier-one
RUN echo "{\"settings\": {\"portMappingEnabled\": true,\"softwareUpdate\": \"disable\",\"allowManagementFrom\": [\"0.0.0.0/0\"]}}" > /var/lib/zerotier-one/local.conf

EXPOSE 9993/tcp
EXPOSE 9993/udp

ENTRYPOINT ["zerotier-one"]
```

**Reply by maxin-cn** [reply]
Sorry. I found that it didn't work above. I build a new zerotier image using the following dockerfile and replace the `zyclonite/zerotier` image in docker-compose.yml.

The dockerfile is:
```
FROM alpine:latest

RUN apk add --no-cache zerotier-one
RUN echo "{\"settings\": {\"portMappingEnabled\": true,\"softwareUpdate\": \"disable\",\"allowManagementFrom\": [\"0.0.0.0/0\"]}}" > /var/lib/zerotier-one/local.conf

EXPOSE 9993/tcp
EXPOSE 9993/udp

ENTRYPOINT ["zerotier-one"]
```
When I looked at the log I found the following error. And I feel strange.
![image](https://user-images.githubusercontent.com/38418898/209148572-2a22f61f-a316-4edd-a041-6a6d1b4573ae.png)

The yaml file is:
```
version: "3"

services:
  zerotier:
    image: mxfordocker/zerotier:1.10.2
    container_name: zu-controller
    restart: unless-stopped
    volumes:
      - ./zerotier-one:/var/lib/zerotier-one
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0
    expose:
      - "9993/tcp"
    ports:
      - "9993:9993/udp"
  zero-ui:
    image: dec0dos/zero-ui:latest
    container_name: zu-main
    build:
      context: .
      dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
    depends_on:
      - zerotier
    volumes:
      - ./zerotier-one:/var/lib/zerotier-one
      - ./data:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://zerotier:9993/
      - ZU_SECURE_HEADERS=false
      - ZU_DEFAULT_USERNAME=admin
      - ZU_DEFAULT_PASSWORD=zero-ui
    ports:
      - "4000:4000"
```

Excuse me, where did I operate wrong?
