### DISCUSSION TITLE
The web site cannot be opened.

### DISCUSSION THREAD

**Discussion by maxin-cn** [dec0dOS/zero-ui#130] [Q&A] [answered]
I installed the docker image according to the tutorial, but I could not open the web interface. And there's no log output at all.
![image](https://user-images.githubusercontent.com/38418898/209097050-e1779377-de3f-491a-a257-c12ad5b536ba.png)

My docker-compose file is here:
```
version: "3"

services:
  zerotier:
    image: zyclonite/zerotier:1.10.1
    container_name: zu-controller
    restart: unless-stopped
    volumes:
      - ./zerotier-one:/var/lib/zerotier-one
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0
    expose:
      - "9993/tcp"
    ports:
      - "9993:9993/udp"
  zero-ui:
    image: dec0dos/zero-ui:latest
    container_name: zu-main
    build:
      context: .
      dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
    depends_on:
      - zerotier
    volumes:
      - ./zerotier-one:/var/lib/zerotier-one
      - ./data:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://zerotier:9993/
      - ZU_SECURE_HEADERS=false
      - ZU_DEFAULT_USERNAME=admin
      - ZU_DEFAULT_PASSWORD=zero-ui
    ports:
      - "4000"
```
