### DISCUSSION TITLE
Zero-ui using zerotier installed on the host server as a private moon

### DISCUSSION THREAD

**Discussion by nhaskel** [dec0dOS/zero-ui#207] [General]
After fumbling around between posts, questions comments and hair pulling I thought I would share how I was able to install zero-ui and point it to a local installed private moon. At this time my setup is for internal use only so i have disabled/removed the https-proxy section.

Install zerotier on the host computer and configure it as necessary for your environment. 
My environment is as follows: Centos 9 (primary moon and docker running only the zero-ui interface), Centos 6 (slave moon) and Windows machines as clients

Set zerotier to allow management from all network interfaces; restart zerotier-one
`echo "{\"settings\": {\"portMappingEnabled\": true,\"softwareUpdate\": \"disable\",\"allowManagementFrom\": [\"0.0.0.0/0\"]}}" > /var/lib/zerotier-one/local.conf`

Follow the installation instructions for zero-ui
Once you have the docker-compose.yml modify it accordingly
```
version: "3"

services:
  #  zerotier:
  #    image: zyclonite/zerotier:1.10.6
  #    container_name: zu-controller
  #    restart: unless-stopped
  #    volumes:
  #      - ./zerotier-one:/var/lib/zerotier-one
  #    environment:
  #      - ZT_OVERRIDE_LOCAL_CONF=true
  #      - ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0
  #    expose:
  #      - "9993/tcp"
  #    ports:
  #      - "9993:9993/udp"
  zero-ui:
    image: dec0dos/zero-ui:latest
    container_name: zu-main
    build:
      context: .
      dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
    volumes:
      - /var/lib/zerotier-one:/var/lib/zerotier-one:ro
      - ./data:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://${hostIP}:9993/
      - ZU_SECURE_HEADERS=false
      - ZU_DEFAULT_USERNAME=admin
      - ZU_DEFAULT_PASSWORD=SOME_NEW_PASSWORD
    ports:
      - "4000:4000"
```    
 
Run the docker compose command and voila, zero-ui is connected to the local installed zerotier-one service running on the server.

Thanks
