### DISCUSSION TITLE
A few questions coming from Zerotier Central

### DISCUSSION THREAD

**Discussion by cristihcd** [dec0dOS/zero-ui#21] [Q&A] [answered]
Hello,

Few questions:

1. How to access the API? I'm using docker-compose with nginx in front for SSL. I retrieved the token from data/db.json. I tried the following curl:
`curl "https://zerotier.example.com/api/network" -H "X-ZT1-AUTH: ${token}"`. The response was: `{"error":"Specify token"}`. I also tried from the docker host ("http://localhost:4000/api/network")

2. Members appear offline in the network detail page, even though the rest of the functionality works (join, authorize, ping, etc).
![image](https://user-images.githubusercontent.com/5652964/135817203-0c899267-c9d3-47d1-9db7-c07a8b31b118.png)

Here is my docker compose file:
zu-controller udp port is 19993
ZU_SECURE_HEADERS=false
```
version: "3.9" 
services: 
  zerotier: 
    image: dec0dos/zerotier-controller:latest 
    container_name: zu-controller 
    restart: unless-stopped 
    volumes: 
      - controller_data:/var/lib/zerotier-one 
    expose: 
      - "9993/tcp" 
    ports: 
      - "19993:19993/udp"
    logging:
      driver: "json-file"
      options:
        max-file: '1'
        max-size: '3m'
  zero-ui: 
    image: dec0dos/zero-ui:latest 
    container_name: zu-main 
    restart: unless-stopped 
    depends_on: 
      - zerotier 
    volumes: 
      - controller_data:/var/lib/zerotier-one 
      - zero-ui_data:/app/backend/data 
    environment: 
      - ZU_CONTROLLER_ENDPOINT=http://zerotier:9993/ 
      - ZU_SECURE_HEADERS=false 
      - ZU_DEFAULT_USERNAME=<...>
      - ZU_DEFAULT_PASSWORD=<...>
    ports: 
      - "4000:4000"
    logging:
      driver: "json-file"
      options:
        max-file: '1'
        max-size: '3m'
volumes: 
  zero-ui_data: 
  controller_data:
```

Here is a snippet from nginx config:

```
server {
    server_name zerotier.example.com;

    location / {
        proxy_pass http://1.2.3.4:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

```
