### DISCUSSION TITLE
How can I use existing SSL certificates?

### DISCUSSION THREAD

**Discussion by l3reathe** [dec0dOS/zero-ui#220] [Q&A]
If I understand correctly, Caddy needs to be disabled. But how can I show the application the certificates already installed on the machine and use SSL with it?

**Comment by l3reathe** [comment]
Resolved.

1. `https-proxy` section of `docker-compose.yml`

```yml
  https-proxy:
    image: caddy:latest
    container_name: zu-https-proxy
    restart: unless-stopped
    depends_on:
      - zero-ui
    volumes:
      - ./caddy:/data/caddy
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/certs:/etc/caddy/certs
    ports:
      - "80:80"
      - "443:443"
```

2. `./caddy/Caddyfile`

```
:80 {
        redir https://{host}{uri} permanent
}

MYDOMAIN.COM {
        reverse_proxy zero-ui:4000
        tls /etc/caddy/certs/fullchain.pem /etc/caddy/certs/privkey.pem
}
```

3. Certificates in `./caddy/certs/`
