### DISCUSSION TITLE
Migrate from ztncui?

### DISCUSSION THREAD

**Discussion by pjv** [dec0dOS/zero-ui#3] [Q&A]
How hard would it be to migrate my networks, their members, settings, etc. from ztncui to zero ui?

Has anyone tried this?

**Comment by dec0dOS** [comment]
Hello! Would you be interested in an automated migration tool?

By the way, It is not hard to do it manually because covering all the installation setups could be a big deal. The main goal of migration from ZTNCUI to ZeroUI is just to swap the controller private key and `controller.d` folder. Or you could use the previous installation of the ZeroTier controller on your host system without swapping and installation of the new ZeroTier controller.
Check out this `docker-compose.yml` as a reference:
```
version: "3.9"

services:
  zero-ui:
    image: dec0dos/zero-ui:latest
    container_name: zu-main
    build:
      context: .
      dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
    volumes:
      - /var/lib/zerotier-one:/var/lib/zerotier-one
      - zero-ui_data:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://127.0.0.1:9993/
      - ZU_SECURE_HEADERS=false
      - ZU_DEFAULT_USERNAME=admin
      - ZU_DEFAULT_PASSWORD=zero-ui
    network_mode: host

volumes:
  zero-ui_data:
```
This setup uses the host system ZeroTier controller.

**Reply by pjv** [reply]
Thank you. I am currently running ztncui like this:

````
version: '3'
services:
  ztncui:
    image: keynetworks/ztncui:latest
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./ztncui/:/opt/key-networks/ztncui/etc/
      - ./zt1/:/var/lib/zerotier-one/
    environment:
      - HTTP_PORT=8000
      - HTTP_ALL_INTERFACES=yes
````

It’s running behind an nginx proxy that is handling SSL/TLS.

In the `./zt1` directory are the following:

````
-rw-r----- 1 2222 2222   24 Dec 11  2019 authtoken.secret
drwx------ 4 2222 2222 4.0K Dec 11  2019 controller.d
-rw-r--r-- 1 2222 2222  141 Dec 11  2019 identity.public
-rw------- 1 2222 2222  270 Dec 11  2019 identity.secret
drwxr-xr-x 2 2222 2222 4.0K Jun 27 05:39 peers.d
-rw-r--r-- 1 2222 2222  570 Apr 14 11:40 planet
-rw-r--r-- 1 2222 2222    2 Jun 28 05:40 zerotier-one.pid
-rw-r--r-- 1 2222 2222    4 Jun 28 05:40 zerotier-one.port
````

So I see the `controller.d` directory. Is `identity.secret` the private key you are talking about?

I guess I could use my existing `./zt1` volume to supply that stuff.

In the `./ztncui` directory is:

````
drwxr-xr-x 2 2222 2222 4.0K May 27 08:51 myfs
-rw------- 1 2222 2222  143 Dec 11  2019 passwd
drwxr-xr-x 2 2222 2222 4.0K Jun 23 11:55 storage
drwxrwxrwx 2 2222 2222 4.0K Dec 11  2019 tls
````

I can’t just supply that directory to `/app/backend/data` can I? 

Is zeroUI data-structure compatible with ztncui?
