### DISCUSSION TITLE
no access to html panel

### DISCUSSION THREAD

**Discussion by alireza787b** [dec0dOS/zero-ui#38] [General]
Sorry for posting this basic question. This is my first experience with Docker
I have not connected any domain to my server and accessed it via IP address. 
What should I type instead of example.com in the docker file while installing? I inserted the IP Address but it's not working and no web page is being shown to me.

**Comment by dec0dOS** [comment]
Hello, @alireza787b.

Please follow the guide in the README on how to disable HTTPS.

> To disable HTTPS, please remove https-proxy from docker-compose.yml, set ZU_SECURE_HEADERS to false and change zero-ui port expose to ports.

**Reply by alireza787b** [reply]
Thanks for the reply
I followed the documentation and disabled the HTTPS... still no access to the page. what exact URL sould I navigate to ? 
http://IP_ADRESS:4000 ? or /app?

This is my docker file before installation
```
 dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
    depends_on:
      - zerotier
    volumes:
      - controller_data:/var/lib/zerotier-one
      - zero-ui_data:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://zerotier:9993/
      - ZU_SECURE_HEADERS=false
      - ZU_DEFAULT_USERNAME=admin
      - ZU_DEFAULT_PASSWORD=zero-ui
    ports:
      - "4000"

volumes:
  zero-ui_data:
  controller_data:
  caddy_data:
```

**Reply by dec0dOS** [reply]
Something like this should work for you (`docker-compose.yml`):
```
version: "3.9"

services:
  zerotier:
    image: dec0dos/zerotier-controller:latest
    container_name: zu-controller
    build:
      context: .
      dockerfile: ./docker/zerotier/Dockerfile
    restart: unless-stopped
    volumes:
      - controller_data:/var/lib/zerotier-one
    expose:
      - "9993/tcp"
    ports:
      - "9993:9993/udp"
  zero-ui:
    image: dec0dos/zero-ui:latest
    container_name: zu-main
    build:
      context: .
      dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
    depends_on:
      - zerotier
    volumes:
      - controller_data:/var/lib/zerotier-one
      - zero-ui_data:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://zerotier:9993/
      - ZU_SECURE_HEADERS=false
      - ZU_DEFAULT_USERNAME=admin
      - ZU_DEFAULT_PASSWORD=zero-ui
    ports:
      - "4000"

volumes:
  zero-ui_data:
  controller_data:
```

Navigate to `http://YOURIP:4000/app`
