### DISCUSSION TITLE
Member's name and description can not save.

### DISCUSSION THREAD

**Discussion by thelittlerocket** [dec0dOS/zero-ui#5] [Q&A] [answered]
Hi @dec0dOS thanks for the project, this is an awesome UI, it runs smoothly, but when I trying to name the members, it won't save, when I reload the page, the member's name, and description disappeared. I may be missing something since there is no one seems to have this problem.
Would like to know if there is a DB or anything? I checked the db.json, but it only contains the network's information.
Thanks.
![Image 2021-07-08 at 1 46 03 AM](https://user-images.githubusercontent.com/75967438/124806785-a6ff5200-df8f-11eb-902d-e3680cd21e96.png)

**Comment by dec0dOS** [comment, marked as answer]
Hi @thelittlerocket!
I don't have any issues with member's name and description saving on my installation. 

Could you try to edit the member's name and then show your browser console log?

Please also provide your server side logs.
`docker-compose logs` for Docker installation.

**Reply by thelittlerocket** [reply]
Hi @dec0dOS 
Thanks for the reply, here is a screen recording of when I editing the field, at the end of the recording, I reload the page, and then the data in the fields are gone.
![Screen Recording 2021-07-08 at 06 15 15 AM](https://user-images.githubusercontent.com/75967438/124835753-66fe9600-dfb4-11eb-8b06-74cb5288d00b.gif)

My compose file, through a reverse proxy to connect using HTTPS, so I disabled the `ZU_SECURE_HEADERS`

```
version: "3.9"

services:
  zerotier:
    image:zerotier-controller
    container_name: zu-controller
    build:
      context: .
      dockerfile: ./docker/zerotier/Dockerfile
    restart: unless-stopped
    volumes:
      - 'controller_data:/var/lib/zerotier-one'
    expose:
      - "9993/tcp"
    ports:
      - "9993:9993/udp"
    logging:
      driver: "json-file"
      options:
        max-file: '1'
        max-size: '3m'
  zero-ui:
    image:zero-ui
    container_name: zu-main
    build:
      context: .
      dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
    depends_on:
      - zerotier
    volumes:
      - 'controller_data:/var/lib/zerotier-one'
      - 'zero-ui_data:/app/backend/data'
    environment:
      #- NODE_ENV=production
      - ZU_SERVE_FRONTEND=true
      - ZU_CONTROLLER_ENDPOINT=http://zerotier:9993/
      - ZU_SECURE_HEADERS=false
      - ZU_DEFAULT_USERNAME=admin
      - ZU_DEFAULT_PASSWORD=password
    ports:
      - "5010:4000"
    logging:
      driver: "json-file"
      options:
        max-file: '1'
        max-size: '3m'
volumes:
  zero-ui_data:
  controller_data:
```
