### DISCUSSION TITLE
nginx reverse proxy

### DISCUSSION THREAD

**Discussion by Op3rat0r** [dec0dOS/zero-ui#64] [Q&A] [answered]
Hi,
I tried to run the zero-ui behind my nginx reverse prox. Thought I can just change the docker-compose.yml, add the ports 80/443 to the docker-ui and I am good to go. But seems not -.- 

Can someone give me a hint how to run the zero-ui behind nginx reverse proxy instead of the "caddy reverse-proxy", would be great! Runing two reverse proxys doesn't work...

Thanks for you help!

**Comment by Op3rat0r** [comment, marked as answer]
I managed the problem by myself. Somehow it is also written in the documentation, how to do it. You need do adjust the docker-compose.yml file like this.
```
version: "3.9"

services:
  zerotier:
    image: dec0dos/zerotier-controller:latest
    container_name: zu-controller
    build:
      context: .
      dockerfile: ./docker/zerotier/Dockerfile
    restart: unless-stopped
    volumes:
      - controller_data:/var/lib/zerotier-one
    expose:
      - "9993/tcp"
    ports:
      - "9993:9993/udp"
  zero-ui:
    image: dec0dos/zero-ui:latest
    container_name: zu-main
    build:
      context: .
      dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
    depends_on:
      - zerotier
    volumes:
      - controller_data:/var/lib/zerotier-one
      - zero-ui_data:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://zerotier:9993/
      - ZU_SECURE_HEADERS=false
      - ZU_DEFAULT_USERNAME=admin
      - ZU_DEFAULT_PASSWORD=VerySecretPassword
    ports:
            - "4000:4000"

volumes:
  zero-ui_data:
  controller_data:
```

In the **nginx configuration** you have to point to http://ip-address:4000 (_IP-Address of the docker host_)
That worked for me.
