### DISCUSSION TITLE
Only Ui with existing controller on host

### DISCUSSION THREAD

**Discussion by axi92** [dec0dOS/zero-ui#67] [Q&A] [answered]
I tried to start only the ui because we already have the controller on the same host as the container.
Already got a caddy on the host acting as a reverse-proxy.
docker-compose.yml
```
  zero-ui:
    image: dec0dos/zero-ui:latest
    container_name: zero-ui
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/lib/zerotier-one:/var/lib/zerotier-one:ro
      - zero-ui_data:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://localhost:9993/
      - ZU_SECURE_HEADERS=true
      - ZU_DEFAULT_USERNAME=<adminname>
      - ZU_DEFAULT_PASSWORD=<randomgenerateduid>
    expose:
      - "4000"
```

I tested the request from an ubuntu container also with -network host and it worked from there: `curl -H "X-ZT1-Auth: $TOKEN" http://localhost:9993/status` There are no logs from this it tries to attach to container and thats all...

Logs:
```
admin@proxy:~/zero-ui$ docker-compose up
Creating zero-ui ... done
Attaching to zero-ui

```
