### DISCUSSION TITLE
Error: socket hang up

### DISCUSSION THREAD

**Discussion by pjv** [dec0dOS/zero-ui#8] [Q&A] [answered]
Trying to bring zero ui up using this docker-compose.yml (I am using an nginx proxy on the host which handles the ssl):

````
version: "3.9"

services:
  zerotier:
    image: dec0dos/zerotier-controller:latest
    container_name: zu-controller
    restart: unless-stopped
    volumes:
      - ./controller_data:/var/lib/zerotier-one
    expose:
      - "9993/tcp"
    ports:
      - "9993:9993/udp"
  zero-ui:
    image: dec0dos/zero-ui:latest
    container_name: zu-main
    restart: unless-stopped
    depends_on:
      - zerotier
    volumes:
      - ./controller_data:/var/lib/zerotier-one
      - zero-ui_data:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://zerotier:9993/
      - ZU_SECURE_HEADERS=false
      - ZU_DEFAULT_USERNAME=pjv
      - ZU_DEFAULT_PASSWORD=zero-ui
    ports:
      - "4000:4000"

volumes:
  zero-ui_data:
````
I am supplying existing data from a working zerotier controller in the `./controller_data` bind mount.

When I bring this up, the `zerotier` service comes up fine. I can do things like:
````
docker exec zu-controller zerotier-cli info
200 info <XXXXXX> 1.6.5 ONLINE
````

...but the zero-ui container throws a loooooong (2990 line) error message that starts with this:
````
zu-main     | node:internal/errors:683
zu-main     |   const ex = new Error(msg);
zu-main     |              ^
zu-main     |
zu-main     | Error: socket hang up
zu-main     |     at connResetException (node:internal/errors:683:14)
zu-main     |     at Socket.socketOnEnd (node:_http_client:471:23)
zu-main     |     at Socket.emit (node:events:406:35)
zu-main     |     at endReadableNT (node:internal/streams/readable:1329:12)
zu-main     |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
zu-main     |   code: 'ECONNRESET',
zu-main     |   config: {
zu-main     |     url: 'status',
zu-main     |     method: 'get',
zu-main     |     headers: {
zu-main     |       Accept: 'application/json, text/plain, */*',
zu-main     |       'X-ZT1-Auth': <secret stuff>,
zu-main     |       'User-Agent': 'axios/0.21.1'
zu-main     |     },
zu-main     |     baseURL: 'http://zerotier:9993/',
zu-main     |     transformRequest: [ [Function: transformRequest] ],
zu-main     |     transformResponse: [ [Function: transformResponse] ],
zu-main     |     timeout: 0,
zu-main     |     adapter: [Function: httpAdapter],
zu-main     |     responseType: 'json',
zu-main     |     xsrfCookieName: 'XSRF-TOKEN',
zu-main     |     xsrfHeaderName: 'X-XSRF-TOKEN',
zu-main     |     maxContentLength: -1,
zu-main     |     maxBodyLength: -1,
zu-main     |     validateStatus: [Function: validateStatus],
zu-main     |     data: undefined
zu-main     |   },
````

I've done some googling on the "socket hang up" error and it seems like there is a very wide variety of causes.

@dec0dOS any ideas?
