### DISCUSSION TITLE
Can't create network

### DISCUSSION THREAD

**Discussion by kautsaridris** [dec0dOS/zero-ui#93] [Q&A]
I using this script, but after build and accessing with this port IP:4000 and than login i can't create a network, no response
FYI i change default port 9993 to 9995 because i running 2 VM VPN Server with one IP Public for specific purpose 
```yml
version: "3.9"

services:
  zerotier:
    image: dec0dos/zerotier-controller:latest
    container_name: zu-controller
    restart: unless-stopped
    volumes:
      - controller_data:/var/lib/zerotier-one
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0
    expose:
      - "9995/tcp"
    ports:
      - "9995:9993/udp"
  zero-ui:
    image: dec0dos/zero-ui:latest
    container_name: zu-main
    build:
      context: .
      dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
    depends_on:
      - zerotier
    volumes:
      - controller_data:/var/lib/zerotier-one
      - zero-ui_data:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://zerotier:9995/
      - ZU_SECURE_HEADERS=false
      - ZU_DEFAULT_USERNAME=admin
      - ZU_DEFAULT_PASSWORD=zero-ui
    ports:
      - "4000:4000"
volumes:
  zero-ui_data:
  controller_data:
```
