### ISSUE TITLE
feat: Ability to disable auth

### ISSUE THREAD

**Issue by cptechie** [dec0dOS/zero-ui#59]
# Feature Request

Can we have an option to disable auth? Would be helpful in scenarios where the site will already be secured behind AD/OAuth.

**Comment by maltegrosse** [comment]
would appreciate this feature and set the UI behind a auth proxy e.g. https://github.com/8gears/keycloak-auth-proxy
some variable like `process.env.ZU_DISABLE_AUTH`

**Comment by maltegrosse** [comment]
as the priority is low, I decided to create a quick no-auth proxy. 
@cptechie see https://github.com/maltegrosse/zero-ui-noauth
lets see how many proxies we can pipe (no-auth, https, auth :)

**Comment by maltegrosse** [comment]
okay, finally got it working: zeroui->no-auth->oauth2 proxy (via keycloak and traefik)

comparable to my post at https://github.com/benjaminbear/docker-ddns-server/issues/16#issuecomment-1098401651
where I used a similar scenario, traefik, oauth service nearly stay the same, the docker-compose for no-auth is like following:

```
version: "3.7"

services:
  zt-ui-noauth:
    image: maltegrosse/zero-ui-noauth:1.0.0
    container_name: zu-ui-noauth-proxy
    restart: unless-stopped
    expose:
      - "9999"
    ports:
      - "9999"
    environment:
      - PROTOCOL=http
      - AUTH_PATH=/auth/login
      - EXPOSE_PORT=9999
      - CONNECT_HOST=zero-ui
      - CONNECT_PORT=4000
      - USER=admin
      - PASSWORD=zero-ui
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.zt.rule=Host(`zt.example.com`)"
      - "traefik.http.routers.zt.entrypoints=https"
      - "traefik.http.routers.zt.tls.certresolver=tx"
      - "traefik.http.routers.zt.middlewares=oauth-errors@file,oauth-auth@file"
      # excluded the api endpoint as I run in some issues...
      - "traefik.http.routers.zt-noauth.rule=Host(`zt.example.com`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.zt-noauth.entrypoints=https"
      - "traefik.http.routers.zt-noauth.tls.certresolver=tx"

    networks:
      - web
  oauth:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
# see other post linked in this comment
....
# dont forget to stay in the same traefik network
networks:
  web:
    external:
      name: traefik_default
```

@dec0dOS in order to provide a oidc sign-out link, could you introduce a new route, e.g. /signout , where u forward here:
https://github.com/dec0dOS/zero-ui/blob/main/frontend/src/components/Bar/Bar.jsx#L39
so i could overwrite /signout with my router and redirect to the openid signout url.

I am not really into react, otherwise I would help :)
