### ISSUE TITLE
bug: `Add Routes` can not work.

### ISSUE THREAD

**Issue by nAnderYang** [dec0dOS/zero-ui#96]
# Bug Report

**ZeroUI version:**

1.4.1(docker container)

**Current behavior:**

zero-ui add more rule in `Managed Routes` , but any node can not find route ,run ` route -n` find only one default route rule.

**Other information:**

![image](https://user-images.githubusercontent.com/28423384/177113282-eb6642c0-63ff-4e10-8791-6072a48d317f.png)

```
shell $ route -n |grep zt
192.168.192.0   0.0.0.0         255.255.255.0   U     0      0        0 zt6olxlqux
shell $
```

**Comment by nAnderYang** [comment]
@dec0dOS 
i change zerotier container version to 1.10.1

docker-compose.yaml
```
version: "3"

services:
  zerotier:
    image: zyclonite/zerotier:1.10.1
  ...
  zero-ui:
    image: dec0dos/zero-ui:1.4.1
    container_name: zero-ui
```
